DROP DATABASE IF EXISTS DB_TCCGRUPO9;
CREATE DATABASE DB_TCCGRUPO9;

USE DB_TCCGRUPO9;

CREATE TABLE USUARIO (
	IDUSUARIO INT NOT NULL PRIMARY KEY AUTO_INCREMENT
	, NOME VARCHAR(100) NOT NULL
	, EMAIL VARCHAR(100) NOT NULL
	, SENHA VARCHAR(45) NOT NULL
);


select * from usuario;