DROP DATABASE IF EXISTS DB_TCCGRUPO9;
CREATE DATABASE DB_TCCGRUPO9;

USE DB_TCCGRUPO9;

CREATE TABLE USUARIO (
	IDUSUARIO INT NOT NULL PRIMARY KEY AUTO_INCREMENT
	, NOME VARCHAR(100)
	, EMAIL VARCHAR(100)
	, SENHA VARCHAR(45)
) ENGINE INNODB;


CREATE TABLE PROJETO (
	IDPROJETO INT NOT NULL PRIMARY KEY AUTO_INCREMENT
	, CURSO VARCHAR(100)
	, TITULO VARCHAR(255)
	, SUBTITULO VARCHAR(100)
    , AUTORES VARCHAR(255)
	, ANO INTEGER(4)
	, SEMESTRE INTEGER(2)
	, ARQUIVO VARCHAR(100)
) ENGINE INNODB;

select * from projeto;
 INSERT INTO PROJETO (CURSO, TITULO, SUBTITULO, AUTORES, ANO, SEMESTRE, ARQUIVO) VALUES ('SENAI', 'SISTEMA DE LAVACAO', NULL,'JOSE', 2015, 1, NULL );