DROP DATABASE IF EXISTS DB_TCCGRUPO9;
CREATE DATABASE DB_TCCGRUPO9;

USE DB_TCCGRUPO9;

CREATE TABLE USUARIO (
	IDUSUARIO INT NOT NULL PRIMARY KEY AUTO_INCREMENT
	, NOME VARCHAR(100)
	, EMAIL VARCHAR(100)
	, SENHA VARCHAR(45)
) ENGINE INNODB;

CREATE TABLE AUTOR (
	IDAUTOR INT NOT NULL PRIMARY KEY AUTO_INCREMENT
	, NOME VARCHAR(100)
	, EMAIL VARCHAR(100)
) ENGINE INNODB;

CREATE TABLE PROJETO (
	IDPROJETO INT NOT NULL PRIMARY KEY AUTO_INCREMENT
	, IDUSUARIO INT
	, CURSO VARCHAR(100)
	, TEMA VARCHAR(255)
	, SUBTITULO VARCHAR(100)
	, DT_PUBLICACAO DATETIME DEFAULT NOW()
	, ARQUIVO VARCHAR(100)
	, CONSTRAINT FK_PROJETO_USUARIO FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDUSUARIO) ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE INNODB;

CREATE TABLE CRIA (
	IDAUTOR INT NOT NULL
	, IDPROJETO INT NOT NULL
	, CONSTRAINT PK_CRIA PRIMARY KEY (IDAUTOR, IDPROJETO)
	, CONSTRAINT FK_CRIA_AUTOR FOREIGN KEY(IDAUTOR) REFERENCES AUTOR (IDAUTOR) ON UPDATE CASCADE ON DELETE CASCADE
	, CONSTRAINT FK_CRIA_PROJETO FOREIGN KEY(IDPROJETO) REFERENCES PROJETO (IDPROJETO)  ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE INNODB;
